
name: TestMavenBuild

on:
  push:
    branches: [ main, '[A-Z]-[0-9]+**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: mvn -B -Dmaven.test.failure.ignore=true package
