name: release

on:
  workflow_dispatch:

jobs:

  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform release and upload artifact to Nexus
        run: mvn -B release:prepare release:perform
